stages:
  - manifests-dist
  - release
  - build-images

# Create artifacts

manifests-dist:
  image: golang:1.23
  stage: manifests-dist
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apt-get update && apt-get install -y make
    - make kustomize
    - make build-installer
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: never
    paths:
      - dist/install.yaml

############## Create release #####################

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: manifests-dist
      artifacts: true
  script:
    - echo "Create Release $TAG"
    - echo $JOB_ID
  rules:
    - if: $CI_COMMIT_TAG
  release:
    assets:
      links:
        - name: dist/install.yaml
          url: $CI_SERVER_URL/$CI_PROJECT_PATH/-/jobs/$JOB_ID/artifacts/download
    name: "$CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_TAG_MESSAGE"

# ############# Build docker images #########################

build-images:
  image: docker:27.3.1
  stage: build-images
  needs: [release]
  services:
    - docker:27.3.1-dind
  rules:
    - if: $CI_COMMIT_TAG

  before_script:
    - apk update && apk add make bash --no-cache
    - echo "user:$CI_REGISTRY_USER -- pwd:$CI_REGISTRY_PASSWORD -- registry:$CI_REGISTRY"
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "$CI_REGISTRY_IMAGE"
    - echo "$CI_COMMIT_TAG"
    - echo "$CI_COMMIT_TAG_MESSAGE"
  script:
    - echo "Build Images, and create release"
    - make docker-build docker-push IMG=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - make deploy IMG=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - make deploy IMG=$CI_REGISTRY_IMAGE:latest
  when: manual
