# permissions for end users to view customcertificates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nginxpm-operator
    app.kubernetes.io/managed-by: kustomize
  name: customcertificate-viewer-role
rules:
- apiGroups:
  - nginxpm-operator.io
  resources:
  - customcertificates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginxpm-operator.io
  resources:
  - customcertificates/status
  verbs:
  - get
