apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxpm-data
  namespace: nginxpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginxpm-letsencrypt
  namespace: nginxpm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
