apiVersion: nginxpm-operator.io/v1
kind: ProxyHost
metadata:
  labels:
    app.kubernetes.io/name: nginxpm-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxyhost-sample
spec:
  token:
    name: token-sample
    namespace: default

  domainNames:
    - example.com

  blockExploits: true
  websocketSupport: true
  cachingEnabled: false
  # Add custom configuration to the proxyhost, at your own risk
  # advancedConfig: ""
  customLocations:
    - locationPath: /
      forward:
        scheme: http
        service:
          name: nginx-service
        # Or you can use the host configuration
        # host:
        #   hostName: 192.168.1.4 # HostName|IP
        #   hostPort: "80"

  forward:
    scheme: http
    service:
      name: nginx-service
    # Or you can use the host configuration
    # host:
    #   hostName: 192.168.1.4 # HostName|IP
    #   hostPort: "80"

  ssl:
    autoCertificateRequest: true # This generates a new certificate or reuses an existing certificate that matches the domain name

    # letsEncryptEmail: user@example.com # used on new certificate request

    # certificateId: 1 # if you know the certificate id of an existing certificate in the nginx-proxy-manager instance

    # customCertificate:
    #   name: custom-certificate-sample

    # letsEncryptCertificate:
    #   name: letsencrypt-certificate-sample

    sslForced: true
    http2Support: true
    # hstsEnabled: false # More info https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
    # hstsSubdomains: false
