apiVersion: v1
kind: Secret
metadata:
  name: nginxpm-secret
type: Opaque
data:
  identity: YWRtaW4=
  secret: c2VjcmV0Cg==

---
apiVersion: nginxpm-operator.io/v1
kind: Token
metadata:
  labels:
    app.kubernetes.io/name: nginxpm-operator
    app.kubernetes.io/managed-by: kustomize
  name: token-sample
spec:
  endpoint: https://localhost:8443
  secret:
    secretName: nginxpm-secret
